# Generated by Django 3.0.8 on 2021-08-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0003_orders_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
    ]
