# Generated by Django 3.0.8 on 2021-08-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_remove_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
